### ISSUE TITLE
Question Routes

### ISSUE THREAD

**Issue by brittdawn** [alexa-skillz/alexa-interview-overflow#5]
#### `GET /questions`
Route for questions resource (list view)

#### `POST /questions`
Route for creating questions

#### `GET /questions/:questionID` 
Route for a specific question (detailed view)

#### `PUT /questions/:questionID` 
Route for updating a specific question (detailed view)

#### `DELETE /questions/:questionID` 
Route for deleting a specific question (detailed view)

*For inspiration, check out Stack Overflow's API: https://api.stackexchange.com/docs*

**Comment by jonathanheemstra** [comment]
@brittdawn can we change the name of this issue to be just Questions routes?

Reason being: this issue is all about the questions endpoint and I am concerned that it's expressing a need to work on endpoints for both questions and answers. I think an answers specific endpoint should have it's own separate issue.
